hmmtuf/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static

from .config import REGIONS_FILES_ROOT
from .config import REGIONS_FILES_URL
from .config import VITERBI_PATHS_FILES_URL
from .config import VITERBI_PATHS_FILES_ROOT
from .config import MEDIA_URL, MEDIA_ROOT

# urlpatterns for the HMMTuf application
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hmmtuf_home.urls')),
    path('load_file/', include('file_loader.urls')),
    path('compute/', include('hmmtuf_compute.urls')),
    path('load_bed/', include('bed_comparator.urls')),
    path('hmmtuf_login/', include('login.urls')),
    #path('region_extractor/', include('region_extractor.urls')),
    path('hmm_creator/', include('hmm_creator.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]


urlpatterns += static(REGIONS_FILES_URL, document_root=REGIONS_FILES_ROOT)
urlpatterns += static(VITERBI_PATHS_FILES_URL, document_root=VITERBI_PATHS_FILES_ROOT)
urlpatterns += static(VITERBI_PATHS_FILES_URL, document_root=VITERBI_PATHS_FILES_ROOT)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)
handler404 = 'hmmtuf_home.views.page_not_found_handler'
handler500 = 'hmmtuf_home.views.server_error_handler'

hmmtuf_compute/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('hmm_viterbi/',
         views.schedule_hmm_viterbi_compute_view, name='schedule_computation_view'),
    path('hmm_group_viterbi/',
         views.schedule_group_viterbi_compute_view, name='schedule_all_viterbi_compute_view'),

    path('view_viterbi_path/<str:task_id>/',
         views.view_viterbi_path, name='view_viterbi_path'),

    path('view_group_viterbi_path/<str:task_id>/',
         views.view_group_viterbi_path, name='view_group_viterbi_path'),

    path('success_schedule_viterbi_computation/<str:task_id>/',
         views.success_schedule_viterbi_compute_view, name='success_schedule_viterbi_computation_view'),

    path('success_schedule_group_viterbi_compute/<str:task_id>/',
         views.success_schedule_group_viterbi_compute_view, name='success_schedule_group_viterbi_compute_view'),

    path('repeats_distances_plot/',
         views.view_repeats_distances_plot, name='repeats_distances_plot'),

    path('viterbi_result_csv/<str:task_id>/',
         views.download_viterbi_result_csv, name=views.download_viterbi_result_csv.__name__),

]

login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
]

hmmtuf_compute/models.py
import copy

from django.db import models
from django.core.exceptions import ObjectDoesNotExist

from compute_engine import INFO
from compute_engine.src.enumeration_types import JobType, JobResultEnum

from hmmtuf.config import USE_CELERY
from hmmtuf_home.models import ComputationModel
from hmmtuf_home.models import HMMModel
from hmmtuf_home.models import RegionGroupTipModel

from .tasks import compute_viterbi_path_task
from .tasks import compute_group_viterbi_path_task as v_group_path_task


class ViterbiComputationModelBase(ComputationModel):
    """
    Base class for Viterbi path calculation model
    """

    # the tip used for the computation
    group_tip = models.ForeignKey(RegionGroupTipModel, on_delete=models.CASCADE)

    # the hmm model used for the computation
    hmm = models.ForeignKey(HMMModel, on_delete=models.CASCADE)

    # start index of the first region in the group
    start_region_idx = models.IntegerField(null=True)

    # end index of the first region in the group
    end_region_idx = models.IntegerField(null=True)

    # flag indicating that the computation uses SPADE
    use_spade = models.BooleanField(default=False)

    class Meta(ComputationModel.Meta):
        abstract = True

    @staticmethod
    def get_as_map(model: object) -> dict:

        model_dict = copy.deepcopy(model.__dict__)
        if '_state' in model_dict:
            model_dict.pop('_state')
        return model_dict


class GroupViterbiComputationModel(ViterbiComputationModelBase):
    """
    Represents a group Viterbi computation task in the DB
    All fields are NULL by default as the computation may fail
    before computing the relevant field. Instances of this class
    are created by the tasks.compute_viterbi_path_task
    which tries to fill in as many fields as possible. Upon successful
    completion of the task all fields should have valid values
    """

    # the type of the computation
    JOB_TYPE = JobType.GROUP_VITERBI.name

    class Meta(ComputationModel.Meta):
        db_table = 'group_viterbi_computation'

    @staticmethod
    def build_from_map(map_data, save):

        try:
            computation = GroupViterbiComputationModel.objects.get(task_id=map_data["task_id"])
            return computation
        except ObjectDoesNotExist:

            computation = ViterbiComputationModel()
            computation.task_id = map_data["task_id"]
            computation.result = map_data["result"]
            computation.error_explanation = map_data["error_explanation"]
            computation.computation_type = GroupViterbiComputationModel.JOB_TYPE
            computation.hmm_name = map_data["hmm_name"]
            computation.group_tip = map_data["group_tip"]
            computation.start_region_idx = map_data["start_region_idx"]
            computation.end_region_idx = map_data["end_region_idx"]

            if save:
                computation.save()
                print("{0} saved computation: {1}".format(INFO, map_data["task_id"]))
            return computation

    @staticmethod
    def compute(data):

        hmm_name = data['hmm_name']

        if USE_CELERY:
            # schedule the computation
            task = v_group_path_task.delay(hmm_name=hmm_name, group_tip=data["group_tip"],
                                           remove_dirs=data["remove_dirs"], use_spade=data["use_spade"])

            return task.id
        else:

            import uuid
            task_id = str(uuid.uuid4())
            v_group_path_task(task_id=task_id, hmm_name=hmm_name,
                              group_tip=data["group_tip"], remove_dirs=data["remove_dirs"],
                              use_spade=data["use_spade"])
            return task_id

    @staticmethod
    def get_invalid_map(task, result):
        data_map = dict()

        data_map["task_id"] = task.id
        data_map["result"] = JobResultEnum.FAILURE.name
        data_map["error_explanation"] = str(result)
        data_map["computation_type"] = JobType.GROUP_VITERBI.name
        data_map["hmm_filename"] = result["hmm_filename"]
        data_map["group_tip"] = result["group_tip"]
        data_map["start_region_idx"] = result["start_region_idx"]
        data_map["end_region_idx"] = result["end_region_idx"]
        return data_map


class ViterbiComputationModel(ViterbiComputationModelBase):
    """
    DB model for a Viterbi computation task
    All fields are NULL by default as the computation may fail
    before computing the relevant field. Instances of this class
    are created by the tasks.compute_viterbi_path_task
    which tries to fill in as many fields as possible. Upon successful
    completion of the task all fields should have valid values
    """

    # the type of the computation
    JOB_TYPE = JobType.VITERBI.name

    class Meta(ComputationModel.Meta):
        db_table = 'viterbi_computation'

    @staticmethod
    def build_from_map(map_data, save):

        """
        Build a ViterbiComputationModel model from map data
        """
        try:
            computation = ViterbiComputationModel.objects.get(task_id=map_data["task_id"])
            return computation
        except ObjectDoesNotExist:

            computation = ViterbiComputationModel()
            computation.task_id = map_data["task_id"]
            computation.result = map_data["result"]
            computation.error_explanation = map_data["error_explanation"]
            computation.computation_type = ViterbiComputationModel.JOB_TYPE
            computation.hmm = map_data["hmm"]
            computation.group_tip = map_data["group_tip"]
            computation.start_region_idx = map_data["start_region_idx"]
            computation.end_region_idx = map_data["end_region_idx"]

            if save:
                computation.save()
                print("{0} saved computation: {1}".format(INFO, map_data["task_id"]))
            return computation

    @staticmethod
    def compute(data):

        hmm_name = data['hmm_name']
        region_filename = data['region_filename']

        if USE_CELERY:

            # schedule the computation
            task = compute_viterbi_path_task.delay(region_filename=region_filename,
                                                   hmm_name=hmm_name,  remove_dirs=data["remove_dirs"],
                                                   use_spade=data["use_spade"])
            return task.id
        else:

            import uuid
            from .tasks import compute_viterbi_path
            task_id = str(uuid.uuid4())
            compute_viterbi_path(task_id=task_id,
                                 region_filename=region_filename, hmm_name=hmm_name,
                                 remove_dirs=data["remove_dirs"], use_spade=data["use_spade"], )
            return task_id

    @staticmethod
    def get_invalid_map(task, result) -> dict:
        data_map = dict()

        data_map["task_id"] = task.id
        data_map["result"] = JobResultEnum.FAILURE.name
        data_map["error_explanation"] = str(result)
        data_map["computation_type"] = JobType.VITERBI.name
        data_map["hmm"] = result["hmm"]
        return data_map

hmmtuf_compute/forms.py
from abc import abstractmethod
from django.http import HttpResponse
from django.template import loader

from compute_engine import OK
from hmmtuf.constants import INVALID_ITEM
from hmmtuf_home.models import HMMModel, RegionModel


class ComputeFormBase(object):

    """
    Base class for computation forms
    """

    def __init__(self, template_html, context, configuration):
        self._template_html = template_html
        self._context = context
        self._configuration = configuration
        self._response = INVALID_ITEM
        self._kwargs = INVALID_ITEM

    @property
    def response(self):
        return self._response

    @response.setter
    def response(self, value):
        self._response = value

    @property
    def context(self):
        return self._context

    @property
    def template_html(self):
        return self._template_html

    @property
    def kwargs(self):
        return self._kwargs

    @kwargs.setter
    def kwargs(self, value):
        self._kwargs = value

    @abstractmethod
    def check(self, request):
        pass


class GroupViterbiComputeForm(ComputeFormBase):

    def __init__(self, template_html, context):
        super(GroupViterbiComputeForm, self).__init__(template_html=template_html,
                                                      context=context, configuration=None)

        self._group_tip = INVALID_ITEM
        self._hmm_name = INVALID_ITEM
        self._remove_dirs = INVALID_ITEM
        self._use_spade = INVALID_ITEM

        self.kwargs = {"hmm_name": self._hmm_name,
                       "group_tip": self._group_tip,
                       "remove_dirs": self._remove_dirs,
                       "use_spade": self._use_spade}

    def check(self, request):

        self._hmm_name = request.POST.get("hmm", "")
        if self._hmm_name == "":
            return not OK

        self._group_tip = request.POST.get("group_tip")

        if self._group_tip != "all":

            objects = RegionModel.objects.filter(group_tip__tip=self._group_tip)

            if len(objects) == 0:
                template = loader.get_template(self._template_html)
                self.context.update({"error_found": True,
                                      "no_seq_chromosome": "No regions for group {0}".format(self._group_tip)})

                self.response = HttpResponse(template.render(self.context, request))
                return not OK

        self._remove_dirs = request.POST.get('remove_dirs', False)
        if self._remove_dirs == 'True':
            self._remove_dirs = True

        self._use_spade = request.POST.get('use_spade', False)
        if self._use_spade == 'True':
            self._use_spade = True

        self.kwargs = {"hmm_name": self._hmm_name,
                       "group_tip": self._group_tip,
                       "remove_dirs": self._remove_dirs,
                       "use_spade": self._use_spade,}
        return OK


class ViterbiComputeForm(ComputeFormBase):

    def __init__(self, template_html, configuration, context):

        super(ViterbiComputeForm, self).__init__(template_html=template_html,
                                                 context=context,
                                                 configuration=configuration)

        self._group_tip = INVALID_ITEM
        self._hmm_name = INVALID_ITEM
        self._remove_dirs = INVALID_ITEM
        self._use_spade = INVALID_ITEM
        self._region_filename = INVALID_ITEM

        self.kwargs = {"hmm_name": self._hmm_name,
                       "group_tip": self._group_tip,
                       "remove_dirs": self._remove_dirs,
                       "use_spade": self._use_spade,
                       "region_filename": self._region_filename}

    def check(self, request):

        # find the HMM
        hmm_name = request.POST.get("hmm", '')
        hmm_model = HMMModel.objects.get(name=hmm_name)
        hmm_filename = hmm_model.file_hmm.name

        checkbox = request.POST.get('remove_dirs', False)

        if checkbox == 'True':
            checkbox = True

        use_spade = request.POST.get('use_spade', False)

        if use_spade == 'True':
            use_spade = True

        region_name = request.POST.get("region", '')
        region = RegionModel.objects.get(name=region_name)

        self.kwargs = {'hmm_name': hmm_name, 'region_filename': region.file_region.name,
                       'hmm_filename': hmm_filename, "remove_dirs": checkbox, "use_spade": use_spade, }

        return OK

templates/hmmtuf_compute/group_viterbi_result_all_view.html
{% extends "base.html" %}
{% block title %}HMMtuf-View Group All Viterbi Path{% endblock title %}
{%block inner_body %}
{% load static %}

<br/>

{% if show_get_results_button %}

<div class="row">
    <div class="col-lg-8 mb-4">
            <h4>Viterbi Group all path calculation task submitted</h4>
            <h5>Task id: {{ task_id }}</h5>
            <h5>Computation  status: {{ task_status }}</h5>

        <a href="/compute/view_group_viterbi_all/{{ task_id }}" class="btn btn-primary">Get Results</a>
    </div>

</div>
{% elif  error_task_failed %}
<div class="row">
    <div class="col-lg-8 mb-4">
        <h4>Viterbi path calculation task FAILED</h4>
        <h5>Task id: {{ task_id }}</h5>
        <h5>ERROR: Task {{ task_id }} failed</h5>
        <h5>MESSAGE: {{ computation.error_explanation }}</h5>
    </div>
</div>
{% else %}

<div class="row">
    <div class="col-lg-12" id="igv-browser">
    </div>
</div>
<br/>

<script>
function hideShowDiv(idStr) {
      var x = document.getElementById(idStr);
      if (x.style.display === "none") {
        x.style.display = "block";
        var button = document.getElementById("show_hmm_model_button").value="Hide HMM Model";
        button.value="Hide HMM Model";
        //console.log("Button value:")
        console.log(button.value);
      }
      else {
        x.style.display = "none";
        var button = document.getElementById("show_hmm_model_button").value="Show HMM Model";
        button.value="Show HMM Model";
        console.log(button.value);
      }
}
</script>

<script src="https://cdn.jsdelivr.net/npm/igv@2.6.2/dist/igv.min.js"></script>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function () {

var options =
        {
            locus: '{{locus}}:{{start_region_idx}}-{{end_region_idx}}',
            flanking: 1000,
            genome: 'hg38',
            tracks: [
                {
                    name: '{{no_wga_seq_name}}',
                    url: '/static/igv_tracks/{{no_wga_tdf_file}}',
                    indexed: false,
                    min:0,
                    max:60,
                    graphType:"lines",
                    roi: [
                        {
                            name: 'TUF',
                            url: '{{tuf_bed_url}}',
                            color: "rgba(200, 18, 10, 0.15)"
                        },
                        {
                            name: 'CORE',
                            url: '{{tdt_bed_url}}',
                            color: "rgba(18, 200, 10, 0.25)"
                        }
                    ]
                },
                {
                    name: '{{wga_seq_name}}',
                    url: '/static/igv_tracks/{{wga_tdf_file}}',
                    indexed: false,
                    min:0,
                    max:60,
                    graphType:"lines",
                    roi: [
                        {
                            name: 'TUF',
                            url: '{{tuf_bed_url}}',
                            color: "rgba(200, 18, 10, 0.15)"
                        },
                        {
                            name: 'CORE',
                            url: '{{tdt_bed_url}}',
                            color: "rgba(18, 200, 10, 0.25)"
                        }
                    ]
                },
                {
                    name: 'TUF',
                    url: '{{tuf_bed_url}}',
                    indexed: false,
                    format: "bed",
                    displayMode: "SQUISHED",
                    height: 30
               },
                {
                    name: 'Normal',
                    url: '{{normal_bed_url}}',
                    format: "bed",
                    indexed: false,
                    displayMode: "SQUISHED",
                    height: 30
               },
               {
                    name: 'Deletion',
                    url: '{{deletion_bed_url}}',
                    indexed: false,
                    format: "bed",
                    displayMode: "SQUISHED",
                    height: 30
               },

                {
                    name: 'Duplication',
                    url: '{{duplication_bed_url}}',
                    indexed: false,
                    format: "bed",
                    displayMode: "SQUISHED",
                    height: 30
               },
                {
                    name: 'GAP',
                    url: '{{gap_bed_url}}',
                    indexed: false,
                    format: "bed",
                    displayMode: "SQUISHED",
                    height: 30
               },
                {
                    name: 'Repeats',
                    url: '{{repeats_bed_url}}',
                    indexed: false,
                    format: "bed",
                    displayMode: "SQUISHED",
                    height: 30
               },
                {
                    name: 'GQUAD',
                    url: '{{quad_bed_url}}',
                    indexed: false,
                    format: "bed",
                    displayMode: "SQUISHED",
                    height: 30
               }
            ]
        };
        var igvDiv = document.getElementById("igv-browser");
        igv.createBrowser(igvDiv, options)
                .then(function (browser) {
                    console.log("Created IGV browser");
                })
});
</script>

<script>
    var svg = d3.select("#canvas");
</script>
{% endif %}
{% endblock inner_body %}

templates/hmmtuf_compute/schedule_compare_sequences_compute_view.html
{% extends "base.html" %}
{% block title %}HMMtuf-Compute Viterbi Sequence Comparison{% endblock title %}
{%block inner_body %}

<br/>
<div class="row">
    <div class="col-lg-8 mb-4">

{% if no_spade %}
        <p>ERROR: HMMtuf not configured with SPADE support</p>
{% else %}

{% if error_empty_hmm_list %}
        <p>ERROR: {{ error_empty_hmm_list }} <a href="/load_file/load_hmm">Create HMM models</a></p>
{% else %}
    {% if error_found %}

        {% if no_seq_chromosome %}
        <p>ERROR: {{ no_seq_chromosome }}. <a href="/load_file/load_region">Load region.</a></p>
        {% else %}
        <p>ERROR: {{ error_msg }}.</a></p>
        {% endif %}
    {% endif %}
    <h4>Schedule group Viterbi path computation</h4>
    <hr/>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="control-group form-group">
        <div class="controls">
            <label>Sequence  tip:</label><br/>
            <select name="group_tip">
                {% for group in sequence_tips %}
                    <option value="{{ group }}">{{ group }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <div class="control-group form-group">
        <div class="controls">
            <label>Max number of sequences in group:</label><br/>
            <input type="number" name="max_num_seqs" value="-1">
        </div>
    </div>

    <div class="control-group form-group">
        <div class="controls">
            <label>Distance  metric:</label><br/>
            <select name="distance_metric">
                {% for name in metrics %}
                    <option value="{{ name }}">{{ name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <button type="submit" class="btn btn-primary">Compute</button>
</form>
</div>
    {% endif %}
    {% endif %}
</div>
{% endblock inner_body %}

templates/hmmtuf_compute/schedule_group_viterbi_compute_view.html
{% extends "base.html" %}
{% block title %}HMMtuf-Compute Group Viterbi Path{% endblock title %}
{%block inner_body %}

<br/>
<div class="row">
    <div class="col-lg-8 mb-4">

{% if error_empty_hmm_list %}
        <p>ERROR: {{ error_empty_hmm_list }} <a href="/load_file/load_hmm">Create HMM models</a></p>
{% elif no_group_list %}
        <p>ERROR: {{ no_group_list }}</p>
{% else %}
    {% if error_found %}
        {% if no_seq_chromosome %}
        <p>ERROR: {{ no_seq_chromosome }}. <a href="/load_file/load_region">Load region.</a></p>
        {% elif no_seq_group %}
        <p>ERROR: {{ no_seq_group }}.</p>
        {% else %}
        <p>ERROR: {{ error_found }}.</a></p>
        {% endif %}
    {% endif %}
    <h4>Schedule group Viterbi path computation</h4>
    <hr/>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="control-group form-group">
        <div class="controls">
            <label>HMM file:</label><br/>
            <select id="id_hmm" name="hmm">
                {% for hmm_name in hmm_names %}
                    <option value="{{ hmm_name }}">{{ hmm_name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <div class="control-group form-group">
        <div class="controls">
            <label>Group tip:</label><br/>
            <select name="group_tip">
                {% for group in group_tips %}
                    <option value="{{ group.tip }}">{{ group.tip }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    {% if use_spade %}
    <input type="checkbox" name="use_spade" value="True">
    <label for="use_spade">Use SPADE</label><br><br>

    <input type="checkbox" name="remove_dirs" value="True">
    <label for="remove_dirs">Remove created directories</label><br><br>
    {% endif %}

    <button type="submit" class="btn btn-primary">Compute</button>
</form>
</div>
    {% endif %}
</div>
{% endblock inner_body %}

templates/hmmtuf_compute/schedule_hmm_multi_viterbi_view.html
{% extends "base.html" %}
{% block title %}HMMtuf-Compute Viterbi Path{% endblock title %}
{%block inner_body %}

<br/>
<div class="row">
    <div class="col-lg-8 mb-4">

{% if error_empty_hmm_list %}
        <p>ERROR: {{ error_empty_hmm_list }} <a href="/load_file/load_hmm">Create HMM models</a></p>
{% else %}
    {% if error_found %}

        {% if no_seq_chromosome %}
        <p>ERROR: {{ no_seq_chromosome }}. <a href="/load_file/load_region">Load region.</a></p>
        {% else %}
        <p>ERROR: {{ error_found }}.</a></p>
        {% endif %}
    {% endif %}
    <h4>Schedule multiple Viterbi path computation</h4>
    <hr/>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="control-group form-group">
        <div class="controls">
            <label>Reference file:</label><br/>
            <select id="id_region" name="reference_files_names">
                {% for name in reference_files_names %}
                    <option value="{{ name }}">{{ name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <div class="control-group form-group">
        <div class="controls">
            <label>HMM file:</label><br/>
            <select id="id_hmm" name="hmm">
                {% for hmm_name in hmm_names %}
                    <option value="{{ hmm_name }}">{{ hmm_name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <div class="control-group form-group">
        <div class="controls">
            <label>Chromosome:</label>
            <input type="text" class="form-control" name="chromosome"><br/>
        </div>
    </div>
    <br/>

    <div class="control-group form-group">
        <div class="controls">
            <label>Group tip:</label><br/>
            <select name="group_tip">
                {% for group in group_tips %}
                    <option value="{{ group.tip }}">{{ group.tip }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <button type="submit" class="btn btn-primary">Compute</button>
</form>
</div>
    {% endif %}
</div>
{% endblock inner_body %}

templates/hmmtuf_compute/schedule_multi_viterbi__compute_view.html
{% extends "base.html" %}
{% block title %}HMMtuf-Compute Viterbi Path{% endblock title %}
{%block inner_body %}

<br/>
<div class="row">
    <div class="col-lg-8 mb-4">

{% if error_empty_hmm_list %}
        <p>ERROR: {{ error_empty_hmm_list }} <a href="/load_file/load_hmm">Create HMM models</a></p>
{% else %}
    {% if error_found %}

        {% if no_seq_chromosome %}
        <p>ERROR: {{ no_seq_chromosome }}. <a href="/load_file/load_region">Load region.</a></p>
        {% else %}
        <p>ERROR: {{ error_found }}.</a></p>
        {% endif %}
    {% endif %}
    <h4>Schedule multiple Viterbi path computation</h4>
    <hr/>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="control-group form-group">
        <div class="controls">
            <label>Reference file:</label><br/>
            <select id="id_region" name="reference_files_names">
                {% for name in reference_files_names %}
                    <option value="{{ name }}">{{ name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <div class="control-group form-group">
        <div class="controls">
            <label>HMM file:</label><br/>
            <select id="id_hmm" name="hmm">
                {% for hmm_name in hmm_names %}
                    <option value="{{ hmm_name }}">{{ hmm_name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <div class="control-group form-group">
        <div class="controls">
            <label>Chromosome:</label>
            <input type="text" class="form-control" name="chromosome"><br/>
        </div>
    </div>
    <br/>

    <div class="control-group form-group">
        <div class="controls">
            <label>Group tip:</label><br/>
            <select name="group_tip">
                {% for group in group_tips %}
                    <option value="{{ group.tip }}">{{ group.tip }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <button type="submit" class="btn btn-primary">Compute</button>
</form>
</div>
    {% endif %}
</div>
{% endblock inner_body %}

templates/hmmtuf_compute/schedule_viterbi_compute_view.html
{% extends "base.html" %}
{% block title %}HMMtuf-Compute Viterbi Path{% endblock title %}
{%block inner_body %}

<br/>
<div class="row">
    <div class="col-lg-8 mb-4">
    {% if error_empty_hmm_list %}
        <p>ERROR: {{ error_empty_hmm_list }} <a href="/load_file/load_hmm">Create HMM models</a></p>
    {% elif error_empty_region_list %}
        <p>ERROR: {{ error_empty_region_list }} <a href="/load_file/load_region">Upload a region file</a></p>
    {% else %}
    <h4>Schedule Viterbi path computation</h4>
    <hr/>

        {% if no_seq_group %}
        <p>ERROR: {{ no_seq_group }}</p>
        {% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="control-group form-group">
        <div class="controls">
            <label>Region file:</label><br/>
            <select id="id_region" name="region">
                {% for region_name in region_names %}
                    <option value="{{ region_name }}">{{ region_name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    <div class="control-group form-group">
        <div class="controls">
            <label>HMM file:</label><br/>
            <select name="hmm">
                {% for hmm_name in hmm_names %}
                    <option value="{{ hmm_name }}">{{ hmm_name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br/>

    {% if use_spade %}
    <input type="checkbox" name="use_spade" value="True">
    <label for="use_spade">Use SPADE</label><br><br>

    <input type="checkbox" name="remove_dirs" value="True">
    <label for="remove_dirs">Remove created directories</label><br><br>
    {% endif %}

    <br/>
    <button type="submit" class="btn btn-primary">Compute</button>
</form>
</div>
</div>
{% endif %}
{% endblock inner_body %}

templates/hmmtuf_compute/success_schedule_compare_sequences_compute_view.html
{% extends "base.html" %}
{% block title %}HMMtuf-Success Schedule Sequence Comparison Computation{% endblock title %}
{%block inner_body %}

<br/>
<div class ="row">
<div class="col-lg-8 mb-4">
    {% if error_msg %}
    <p>ERROR: {{ error_msg }}</p><br/>
    {% endif %}
<p>Successfully scheduled sequence comparison computation. <a href="/compute/view_sequence_comparison/{{task_id}}" target="_blank">View task state</a></p><br/>
</div>
</div>
{% endblock inner_body %}

templates/hmmtuf_compute/success_schedule_group_viterbi_compute_all_view.html
{% extends "base.html" %}
{% block title %}HMMtuf-Success Schedule Group Viterbi All Computation{% endblock title %}
{%block inner_body %}

<br/>
<div class ="row">
<div class="col-lg-8 mb-4">
    {% if error_msg %}
    <p>ERROR: {{ error_msg }}</p><br/>
    {% endif %}
<p>Successfully scheduled group-region Viterbi computation. <a href="/compute/view_group_viterbi_all/{{task_id}}" target="_blank">View task state</a></p><br/>
</div>
</div>
{% endblock inner_body %}